# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(408, 287)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.urlArea = QtGui.QLineEdit(self.centralwidget)
        self.urlArea.setObjectName(_fromUtf8("urlArea"))
        self.horizontalLayout.addWidget(self.urlArea)
        self.getButton = QtGui.QPushButton(self.centralwidget)
        self.getButton.setObjectName(_fromUtf8("getButton"))
        self.horizontalLayout.addWidget(self.getButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.videoQualityComboBox = QtGui.QComboBox(self.centralwidget)
        self.videoQualityComboBox.setObjectName(_fromUtf8("videoQualityComboBox"))
        self.videoQualityComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.videoQualityComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.audioQualityComboBox = QtGui.QComboBox(self.centralwidget)
        self.audioQualityComboBox.setObjectName(_fromUtf8("audioQualityComboBox"))
        self.audioQualityComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.audioQualityComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.destPathArea = QtGui.QLineEdit(self.centralwidget)
        self.destPathArea.setObjectName(_fromUtf8("destPathArea"))
        self.horizontalLayout_3.addWidget(self.destPathArea)
        self.browseButton = QtGui.QToolButton(self.centralwidget)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.horizontalLayout_3.addWidget(self.browseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.downloadButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadButton.sizePolicy().hasHeightForWidth())
        self.downloadButton.setSizePolicy(sizePolicy)
        self.downloadButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.downloadButton.setFlat(False)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.horizontalLayout_4.addWidget(self.downloadButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 408, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionAbout1 = QtGui.QAction(MainWindow)
        self.actionAbout1.setObjectName(_fromUtf8("actionAbout1"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.videoQualityComboBox)
        self.label_3.setBuddy(self.audioQualityComboBox)
        self.label_2.setBuddy(self.destPathArea)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.urlArea, self.getButton)
        MainWindow.setTabOrder(self.getButton, self.videoQualityComboBox)
        MainWindow.setTabOrder(self.videoQualityComboBox, self.audioQualityComboBox)
        MainWindow.setTabOrder(self.audioQualityComboBox, self.destPathArea)
        MainWindow.setTabOrder(self.destPathArea, self.browseButton)
        MainWindow.setTabOrder(self.browseButton, self.downloadButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.getButton.setStatusTip(_translate("MainWindow", "Get the File Info", None))
        self.getButton.setText(_translate("MainWindow", "Get!", None))
        self.label.setText(_translate("MainWindow", "Select Video Quality", None))
        self.videoQualityComboBox.setItemText(0, _translate("MainWindow", "Best Quality", None))
        self.label_3.setText(_translate("MainWindow", "Select Audio Quality", None))
        self.audioQualityComboBox.setItemText(0, _translate("MainWindow", "Best Quality", None))
        self.label_2.setText(_translate("MainWindow", "Save To", None))
        self.browseButton.setText(_translate("MainWindow", "...", None))
        self.downloadButton.setStatusTip(_translate("MainWindow", "Download the Selected File", None))
        self.downloadButton.setText(_translate("MainWindow", "Download", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit the App", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionAbout1.setText(_translate("MainWindow", "About", None))

